[package]
name = "rcat-tui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Ratatui-based interactive TUI for rcat"

[dependencies]
ratatui = { workspace = true }
crossterm = { workspace = true }
anyhow = { workspace = true }
rcat-core = { path = "../rcat-core" }
memmap2 = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = "3"
